### ISSUE TITLE
ParentID is missing in search result  from search form 

### ISSUE THREAD

**Issue by thomaspaulson** [silverstripe-labs/silverstripe-secureassets#22]
I trying to make this module in upgrading website from 2.4 to 3.1, and i love this module, 

I am trying to set permission for only in certaion group so i set 'Only these people in the list', but i search result file get listed.

it is already mention ParentID is missing search result  from search-form for File.

But when I looked futher how search work, i found the this code framework/model/MySQLDatabase.php 
[line 905](https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/MySQLDatabase.php#L905)

I do not understand what is  "ParentID" => "_utf8''", when i removed  "_utf8''" the search result works fine. secureassets module works awesome

```
		// Make column selection lists
		$select = array(
			'SiteTree' => array(
				"ClassName", "$baseClasses[SiteTree].\"ID\"", "ParentID",
				"Title", "MenuTitle", "URLSegment", "Content",
				"LastEdited", "Created",
				"Filename" => "_utf8''", "Name" => "_utf8''",
				"Relevance" => $relevance['SiteTree'], "CanViewType"
			),
			'File' => array(
				"ClassName", "$baseClasses[File].\"ID\"", "ParentID" => "_utf8''",
				"Title", "MenuTitle" => "_utf8''", "URLSegment" => "_utf8''", "Content",
				"LastEdited", "Created",
				"Filename", "Name",
				"Relevance" => $relevance['File'], "CanViewType" => "NULL"
			),
		);
```

**Comment by mikeyc7m** [comment]
rather than hack the core, i just use this fix in SecureFileExtension:
`$file = $this->owner;`
`if( $file->ParentID == "" ){`
`	$file = DataObject::get($file->ClassName)->byID($file->ID);`
`}`

I'll open a pull request.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/5144
